-- Unified view of adhoc metadata triggers for DEV and TEST environments
-- Exposes the METADATA_CONFIG_TABLE_ELT_ADHOC table with environment context
-- Located in DATA_VAULT_TEMP.MIGRATION for extensibility
-- Note: UAT and PROD tables are not yet deployed

CREATE OR REPLACE VIEW DATA_VAULT_TEMP.MIGRATION.METADATA_CONFIG_TABLE_ELT_ADHOC_VW AS
-- Combine DEV and TEST adhoc triggers with environment context
SELECT
  METADATA_CONFIG_KEY,
  LOGICAL_NAME,
  DATABASE_NAME,
  SCHEMA_NAME,
  SOURCE_TABLE_NAME,
  LOAD_START_DATETIME,
  LOAD_END_DATETIME,
  LAST_TRIGGER_TIMESTAMP,
  ERROR_STATUS,
  PAYLOAD,
  'DEV' AS ENVIRONMENT
FROM STAGE_DEV.ELT.METADATA_CONFIG_TABLE_ELT_ADHOC
UNION ALL
SELECT
  METADATA_CONFIG_KEY,
  LOGICAL_NAME,
  DATABASE_NAME,
  SCHEMA_NAME,
  SOURCE_TABLE_NAME,
  LOAD_START_DATETIME,
  LOAD_END_DATETIME,
  LAST_TRIGGER_TIMESTAMP,
  ERROR_STATUS,
  PAYLOAD,
  'TEST' AS ENVIRONMENT
FROM STAGE_TEST.ELT.METADATA_CONFIG_TABLE_ELT_ADHOC
ORDER BY LAST_TRIGGER_TIMESTAMP DESC;
