CREATE OR REPLACE VIEW DATA_VAULT_TEMP.MIGRATION.METADATA_RECENT_RUNS_VW AS
-- Unified recent runs view combining adhoc triggers and audit log runs.
-- Consumers can query with `WHERE SOURCE_TABLE = '<tbl>' ORDER BY RUN_TS DESC LIMIT 20`.

SELECT
  m.METADATA_CONFIG_KEY,
  m.LOGICAL_NAME,
  m.DATABASE_NAME        AS SOURCE_DATABASE,
  m.SCHEMA_NAME          AS SOURCE_SCHEMA,
  m.SOURCE_TABLE_NAME    AS SOURCE_TABLE,
  'ADHOC'                AS RUN_SOURCE,
  a.LOAD_START_DATETIME  AS RUN_START_DATETIME,
  a.LOAD_END_DATETIME    AS RUN_END_DATETIME,
  a.LAST_TRIGGER_TIMESTAMP AS RUN_TS
FROM STAGE_DEV.ELT.METADATA_CONFIG_TABLE_ELT AS m
JOIN STAGE_DEV.ELT.METADATA_CONFIG_TABLE_ELT_ADHOC AS a
  ON m.METADATA_CONFIG_KEY = a.METADATA_CONFIG_KEY

UNION ALL

SELECT
  m.METADATA_CONFIG_KEY,
  m.LOGICAL_NAME,
  al.SOURCE_DATABASE     AS SOURCE_DATABASE,
  al.SOURCE_SCHEMA       AS SOURCE_SCHEMA,
  al.SOURCE_TABLE        AS SOURCE_TABLE,
  'AUDIT'                AS RUN_SOURCE,
  NULL                   AS RUN_START_DATETIME,
  NULL                   AS RUN_END_DATETIME,
  al.RUN_DATE_TIME       AS RUN_TS
FROM STAGE_DEV.ELT.METADATA_CONFIG_TABLE_ELT AS m
JOIN STAGE_DEV.ELT.ELT_LOAD_LOG AS al
  ON (
    UPPER(COALESCE(m.SOURCE_TABLE_NAME, '')) = UPPER(COALESCE(al.SOURCE_TABLE, ''))
    OR UPPER(COALESCE(m.SOURCE_TABLE_NAME, '')) = UPPER(COALESCE(al.LOAD_NAME, ''))
    OR UPPER(COALESCE(m.SOURCE_TABLE_NAME, '')) = UPPER(COALESCE(al.LOAD_ID, ''))
  );
