create or replace TABLE STAGE_DEV.ELT.ELT_JOB_RUN_ERROR (
	ERROR_ID VARCHAR(100),
	RUN_ID VARCHAR(100),
	ERROR_TIMESTAMP TIMESTAMP_NTZ(9),
	ERROR_MESSAGE VARCHAR(16777216),
	SOURCE_STAGE VARCHAR(255)
)
COMMENT='Snowflake metadata table for storing the Job run erros.'
;


select DATE_TRUNC('DAY',ERROR_TIMESTAMP)::DATE as DATEE, ERROR_MESSAGE as MSG, SOURCE_STAGE, COUNT(DATE_TRUNC('DAY',ERROR_TIMESTAMP)::DATE), 
from STAGE_DEV.ELT.ELT_JOB_RUN_ERROR
group by 1, 2, 3
order by 1 desc, 2 desc
limit 20;


ERROR_ID	RUN_ID	ERROR_TIMESTAMP	ERROR_MESSAGE	SOURCE_STAGE
40c85890-4466-4b6b-a0aa-6a6f53734e85		2025-12-12 08:01:51.640	Operation on target Incremental Load SQL Server Data_No_CT failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
2e917c87-5372-4cad-96b5-2e730ce98e57		2025-12-03 13:52:20.781	InternalServerError executing request	Create_Snowflake_Objects
0c488f59-d0ae-465d-b43b-2db5bf0508f4		2025-07-18 05:04:10.743	Operation on target Insert Audit Log Columns failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 000904 (42000): SQL compilation error: error line 27 at position 4
invalid identifier SUCCEEDED,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
c671fb7a-1e16-4d0e-a6dc-2e66af1f5f01		2025-07-17 05:04:56.071	Operation on target Insert Audit Log Columns failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 000904 (42000): SQL compilation error: error line 27 at position 4
invalid identifier SUCCEEDED,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
1e507782-50c1-46e8-be68-fdb9a24cf5dd		2025-09-30 00:18:45.501	Error Detected, check ADF logs	Create_Snowflake_Objects
a554f653-4808-48ad-9151-19639affdeb4		2026-01-14 01:44:50.927	Error Detected, check ADF logs	Create_Snowflake_Objects
128d0139-fc75-4532-8124-2e0135889211		2025-12-11 21:01:37.782	Operation on target Full Load SQL Server Data failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
de6f183b-e1f9-4642-8171-2e6d9d22a5ed		2025-12-12 08:02:04.846	Operation on target Full Load SQL Server Data failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
f6238953-3c02-4c3e-8a37-496bcfff5891		2025-11-14 06:52:45.663	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
c671fb7a-1e16-4d0e-a6dc-2e66af1f5f01		2025-07-17 05:08:22.058	Operation on target Insert Audit Log Columns failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 000904 (42000): SQL compilation error: error line 27 at position 4
invalid identifier SUCCEEDED,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
f33a7a86-81be-4c70-b991-f3af7d2cdce2		2025-11-13 12:56:24.589	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
a1bbce83-1618-47c9-9e22-4523f2b85603		2025-05-28 17:48:32.955	Error Detected, check ADF logs	Create_Snowflake_Objects
a554f653-4808-48ad-9151-19639affdeb4		2026-01-14 01:44:35.864	Error Detected, check ADF logs	Create_Snowflake_Objects
d7644652-c74a-4f30-9095-cebacbc7a83a		2025-08-08 14:48:23.605	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: BI-RPT-TEST, Database: CRESTA, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "CRESTA" requested by the login. The login failed.
Login failed for user SCANsvc-heart-adf-np.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
ebbb3dba-a225-41c4-9a4f-cd7436d83fc7		2025-12-12 12:01:45.781	Operation on target Full Load SQL Server Data failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
6173c7ff-67fb-42f0-87c8-3960381d464c		2025-11-14 07:11:16.964	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
aec93398-ff9d-4514-badf-14ff934d12ec		2025-11-13 16:54:18.764	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
9afd7da9-4fc4-4a64-af3b-fd2e0c0f2436		2025-12-09 04:18:35.299	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: BI-RPT-PROD, Database: SCANDS_Prod, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "SCANDS_Prod" requested by the login. The login failed.
Login failed for user SCANsvc-heart-adf-np.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
c671fb7a-1e16-4d0e-a6dc-2e66af1f5f01		2025-07-17 05:05:10.633	Operation on target Insert Audit Log Columns failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 000904 (42000): SQL compilation error: error line 27 at position 4
invalid identifier SUCCEEDED,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
cbde112e-0180-4b7d-8ebe-15a6a173c125		2025-08-14 11:44:52.130	Operation on target Resume Truncate Stage Task - Full failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 091421 (22000): Unable to update graph with root task STAGE_DEV.PRODUCT_DBO_LANDING.TASK_TRUNCATE_UTILIZATION_VENDOR_INPUT since that root task is not suspended.,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
e5571388-3d1f-4d52-bce4-4fa0189e8592		2025-10-26 03:07:26.561	Error Detected, check ADF logs	Create_Snowflake_Objects
f216ab57-1068-44d1-89a0-cd75938d6cba		2025-11-13 13:14:02.954	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
353c7f71-0627-4827-8e86-86cdd3328bd0		2025-07-16 05:06:52.899	Operation on target Insert Audit Log Columns failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 000904 (42000): SQL compilation error: error line 27 at position 12
invalid identifier SUCCEEDED,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
aec93398-ff9d-4514-badf-14ff934d12ec		2025-11-13 16:53:00.881	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
a62112a9-a784-4370-9ebe-a1e81c86b1cb		2025-08-29 10:59:25.782	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 002003 (02000): SQL compilation error:
Schema STAGE_DEV.BIDPROCESS_DBO_LANDING does not exist or not authorized.,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
71be6944-b627-4541-bdaa-71e4f02d53d5		2025-09-03 13:11:02.624	Operation on target Full Load SQL Server Data failed: ErrorCode=ParquetJavaInvocationException,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=An error occurred when invoking java, message: java.lang.IllegalArgumentException:No enum constant org.apache.parquet.schema.OriginalType.HRS
total entry:11
java.lang.Enum.valueOf(Unknown Source)
org.apache.parquet.schema.OriginalType.valueOf(OriginalType.java:24)
org.apache.parquet.schema.MessageTypeParser.addPrimitiveType(MessageTypeParser.java:182)
org.apache.parquet.schema.MessageTypeParser.addType(MessageTypeParser.java:113)
org.apache.parquet.schema.MessageTypeParser.addGroupTypeFields(MessageTypeParser.java:101)
org.apache.parquet.schema.MessageTypeParser.parse(MessageTypeParser.java:94)
org.apache.parquet.schema.MessageTypeParser.parseMessageType(MessageTypeParser.java:84)
com.microsoft.datatransfer.bridge.parquet.ParquetWriterBuilderBridge.getSchema(ParquetWriterBuilderBridge.java:198)
com.microsoft.datatransfer.bridge.parquet.ParquetWriterBuilderBridge.build(ParquetWriterBuilderBridge.java:170)
com.microsoft.datatransfer.bridge.parquet.ParquetWriterBridge.open(ParquetWriterBridge.java:13)
com.microsoft.datatransfer.bridge.parquet.ParquetFileBridge.createWriter(ParquetFileBridge.java:27)
.,Source=Microsoft.DataTransfer.Richfile.ParquetTransferPlugin,Type=Microsoft.DataTransfer.Richfile.JniExt.JavaBridgeException,Message=,Source=Microsoft.DataTransfer.Richfile.HiveOrcBridge,	Create_Snowflake_Objects
97b89257-e106-47c6-8c4c-92523c0624d6		2025-11-20 15:18:43.202	InternalServerError executing request	Create_Snowflake_Objects
a62112a9-a784-4370-9ebe-a1e81c86b1cb		2025-08-29 10:59:11.119	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 002003 (02000): SQL compilation error:
Schema STAGE_DEV.BIDPROCESS_DBO_LANDING does not exist or not authorized.,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
0c488f59-d0ae-465d-b43b-2db5bf0508f4		2025-07-18 05:05:23.546	Operation on target Insert Audit Log Columns failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 000904 (42000): SQL compilation error: error line 27 at position 4
invalid identifier SUCCEEDED,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
c04bfbf6-9c3a-4cc6-862d-ad5387731696		2025-07-29 09:23:06.208	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 001003 (42000): SQL compilation error:
syntax error line 1 at position 126 unexpected (.,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
194d4ad5-5c40-4cd4-b6d9-67b34c455f55		2025-11-14 06:33:36.347	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
2e917c87-5372-4cad-96b5-2e730ce98e57		2025-12-03 13:54:32.677	Operation on target Full Load SQL Server Data failed: ErrorCode=JniException,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=An error occurred when invoking Java Native Interface.,Source=Microsoft.DataTransfer.Common,Type=JNI.JniReturnException,Message=Cannot create JVM: JNI return code [-4][JNI call failed: memory error.],Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
9597ca12-7d83-477f-8256-4eaca8851469		2025-11-04 15:17:55.525	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: DS-STAGE-TEST, Database: MedhokODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "MedhokODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
2d5cd34d-13cc-44b3-97a3-fecf530911fb		2025-11-14 10:35:26.168	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
c8050b8a-cd96-4dfc-a89e-1ed93efb12e5		2025-12-12 11:01:55.129	Operation on target Full Load SQL Server Data failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
6173c7ff-67fb-42f0-87c8-3960381d464c		2025-11-14 07:10:03.185	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
aec93398-ff9d-4514-badf-14ff934d12ec		2025-11-13 16:52:58.039	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
55ae980b-3c6f-4301-bd66-67dfb01aae7b		2025-12-11 23:01:29.473	Operation on target Incremental Load SQL Server Data_No_CT failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
353c7f71-0627-4827-8e86-86cdd3328bd0		2025-07-16 05:05:27.194	Operation on target Insert Audit Log Columns failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 000904 (42000): SQL compilation error: error line 27 at position 12
invalid identifier SUCCEEDED,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
0f1c07e5-987d-4bbd-8581-f040d1e4f67e		2025-12-12 07:02:04.560	Operation on target Full Load SQL Server Data failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
194d4ad5-5c40-4cd4-b6d9-67b34c455f55		2025-11-14 06:33:24.487	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
f33a7a86-81be-4c70-b991-f3af7d2cdce2		2025-11-13 12:54:30.558	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
9597ca12-7d83-477f-8256-4eaca8851469		2025-11-04 15:17:58.849	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: DS-STAGE-TEST, Database: MedhokODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "MedhokODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
f6238953-3c02-4c3e-8a37-496bcfff5891		2025-11-14 06:52:54.381	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
194d4ad5-5c40-4cd4-b6d9-67b34c455f55		2025-11-14 06:33:34.215	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
f2fa571a-ef77-4712-8925-475dde73107a		2025-11-12 01:06:27.424	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: BI-RPT-TEST, Database: CLAIMS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "CLAIMS" requested by the login. The login failed.
Login failed for user SCANsvc-heart-adf-np.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
fa662356-f6b1-4453-9606-4bb25194f96c		2025-12-11 20:02:38.000	Operation on target Full Load SQL Server Data failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
a0f8f825-4abb-40a1-85fb-84de272ca959		2026-01-05 22:18:10.375	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: ScanODS-Dev, Database: MDS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Login failed for user scansvc-heart-adf-np.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
353c7f71-0627-4827-8e86-86cdd3328bd0		2025-07-16 05:05:21.804	Operation on target Insert Audit Log Columns failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 000904 (42000): SQL compilation error: error line 27 at position 12
invalid identifier SUCCEEDED,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
996ae489-24b1-4429-95a0-df78bbdd9321		2025-06-13 10:25:34.324	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: HCISYS-DB1-TEST, Database: HCIReports, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "HCIReports" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
55ae980b-3c6f-4301-bd66-67dfb01aae7b		2025-12-11 23:01:20.971	Operation on target Incremental Load SQL Server Data_No_CT failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
a554f653-4808-48ad-9151-19639affdeb4		2026-01-14 01:43:21.214	Error Detected, check ADF logs	Create_Snowflake_Objects
98eb375d-0de0-496d-bffe-caa04a906e7f		2025-11-12 04:01:21.206	Operation on target Truncate raw table failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 002003 (02000): SQL compilation error:
Schema STAGE_DEV.HEDIS_DBO_HIS does not exist or not authorized.,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
9fa533b5-b423-49c0-a63f-ba9d691f2efd		2025-08-14 11:15:04.286	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
4196cb28-f417-41c1-938d-0131dc14802d		2025-11-14 00:22:50.895	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
6173c7ff-67fb-42f0-87c8-3960381d464c		2025-11-14 07:07:25.993	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
c04bfbf6-9c3a-4cc6-862d-ad5387731696		2025-07-29 09:27:57.537	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
bba6bcc9-7801-4998-b3cc-5c0fe3a41655		2025-08-28 03:07:38.416	Error Detected, check ADF logs	Create_Snowflake_Objects
194d4ad5-5c40-4cd4-b6d9-67b34c455f55		2025-11-14 06:34:45.154	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
f33a7a86-81be-4c70-b991-f3af7d2cdce2		2025-11-13 12:52:27.939	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
58e4915f-6e77-4e54-b7c8-738442ae6187		2025-08-04 12:37:16.755	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: DS-Stage-TEST, Database: SCANDS_FINANCE, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "SCANDS_FINANCE" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
ebbb3dba-a225-41c4-9a4f-cd7436d83fc7		2025-12-12 12:01:58.626	Operation on target Full Load SQL Server Data failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
8a103115-adc4-45b2-9c00-56116f5c994b		2025-12-12 11:01:31.700	Operation on target Incremental Load SQL Server Data_No_CT failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
4196cb28-f417-41c1-938d-0131dc14802d		2025-11-14 00:20:27.667	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
353c7f71-0627-4827-8e86-86cdd3328bd0		2025-07-16 05:05:49.990	Operation on target Insert Audit Log Columns failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 000904 (42000): SQL compilation error: error line 27 at position 12
invalid identifier SUCCEEDED,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
4196cb28-f417-41c1-938d-0131dc14802d		2025-11-14 00:21:27.366	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
ed3e4e5b-93dd-4a64-98c8-203470a39123		2025-10-30 04:01:50.403	Operation on target Truncate raw table failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 002003 (02000): SQL compilation error:
Schema STAGE_DEV.HEDIS_DBO_HIS does not exist or not authorized.,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
56ca5945-c529-4fc7-aaed-3c83a0d7575c		2025-11-11 23:46:53.940	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 002003 (02000): SQL compilation error:
Schema STAGE_DEV.CLAIMS_DBO_LANDING does not exist or not authorized.,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
4196cb28-f417-41c1-938d-0131dc14802d		2025-11-14 00:22:40.736	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
f33a7a86-81be-4c70-b991-f3af7d2cdce2		2025-11-13 12:56:04.294	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
194d4ad5-5c40-4cd4-b6d9-67b34c455f55		2025-11-14 06:36:10.470	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
f33a7a86-81be-4c70-b991-f3af7d2cdce2		2025-11-13 12:54:41.782	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
86f87f29-8c38-46e4-aecd-da0a58ec9b0e		2025-09-26 08:20:13.459	Error Detected, check ADF logs	Create_Snowflake_Objects
f216ab57-1068-44d1-89a0-cd75938d6cba		2025-11-13 13:10:48.800	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
e8d5f973-78cc-488a-9cce-6473b835ff61		2025-08-28 05:02:11.866	Operation on target Full Load SQL Server Data failed: ErrorCode=JniException,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=An error occurred when invoking Java Native Interface.,Source=Microsoft.DataTransfer.Common,Type=JNI.JniReturnException,Message=Cannot create JVM: JNI return code [-1][JNI call failed due to unknown JNI error.],Source=Microsoft.DataTransfer.Richfile.HiveOrcBridge,	Create_Snowflake_Objects
2e917c87-5372-4cad-96b5-2e730ce98e57		2025-12-03 14:00:03.720	InternalServerError executing request	Create_Snowflake_Objects
bb967e8c-f321-41b4-9d70-77d44a52ea62		2025-12-12 01:04:30.384	Operation on target Full Load SQL Server Data failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
76be29d2-ae04-44dd-9d80-5f10db6bbce3		2025-06-16 09:36:10.695	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 002003 (02000): SQL compilation error:
Schema STAGE_DEV.HCIREPORTS_DBO_LANDING does not exist or not authorized.,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
9597ca12-7d83-477f-8256-4eaca8851469		2025-11-04 15:19:26.083	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: DS-STAGE-TEST, Database: MedhokODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "MedhokODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
0c488f59-d0ae-465d-b43b-2db5bf0508f4		2025-07-18 05:10:49.346	Operation on target Insert Audit Log Columns failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 000904 (42000): SQL compilation error: error line 27 at position 4
invalid identifier SUCCEEDED,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
20469e8d-96d3-4a77-b820-889ded44b40e		2025-09-03 12:48:10.598	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 002003 (02000): SQL compilation error:
Schema STAGE_DEV.BIR_OBJECTS_DBO_LANDING does not exist or not authorized.,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
ddd8dcc0-c96c-4f3f-8784-e3f2fb2c9e99		2025-09-22 03:25:07.539	Error Detected, check ADF logs	Create_Snowflake_Objects
6ed12a8f-1b6c-4138-9a1f-4138141e3eeb		2025-08-12 03:02:49.639	Operation on target Incremental Load SQL Server Data_No_CT failed: ErrorCode=JniException,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=An error occurred when invoking Java Native Interface.,Source=Microsoft.DataTransfer.Common,Type=JNI.JniReturnException,Message=Cannot create JVM: JNI return code [-1][JNI call failed due to unknown JNI error.],Source=Microsoft.DataTransfer.Richfile.HiveOrcBridge,	Create_Snowflake_Objects
73d8cad2-de9a-41d6-9504-fce47841ea65		2025-11-04 03:29:01.827	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
0c488f59-d0ae-465d-b43b-2db5bf0508f4		2025-07-18 05:05:11.836	Operation on target Insert Audit Log Columns failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 000904 (42000): SQL compilation error: error line 27 at position 4
invalid identifier SUCCEEDED,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
089aa6d8-11d5-4d33-ab24-a0ec4031993e		2025-12-11 17:01:31.836	Operation on target Incremental Load SQL Server Data_No_CT failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
6c203776-1fe6-44c0-8353-51971acfc55e		2025-08-25 21:51:16.640	Error Detected, check ADF logs	Create_Snowflake_Objects
aec93398-ff9d-4514-badf-14ff934d12ec		2025-11-13 16:53:39.514	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
cff53347-53a5-400d-a018-113046e98fc4		2025-11-25 05:52:29.264	Error Detected, check ADF logs	Create_Snowflake_Objects
de664e77-a369-435a-a0a8-da0fe8d5761c		2025-09-06 18:20:25.338	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: EDI-TEST01, Database: DELEGATEDAUTHS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "DELEGATEDAUTHS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
6173c7ff-67fb-42f0-87c8-3960381d464c		2025-11-14 07:09:59.564	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
aec93398-ff9d-4514-badf-14ff934d12ec		2025-11-13 16:51:49.416	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
c85c24c3-46c4-4d46-8de7-aca3da5d66c4		2025-09-25 10:56:51.782	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 002003 (02000): SQL compilation error:
Schema STAGE_DEV.CARE_ALERT_DBO_LANDING does not exist or not authorized.,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
234db8c5-9297-4cf8-9251-9f40b0a392fb		2025-12-11 19:02:07.279	Operation on target Full Load SQL Server Data failed: ErrorCode=JreNotFound,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Java Runtime Environment cannot be found on the Self-hosted Integration Runtime machine. It is required for parsing or writing to Parquet/ORC files. Make sure Java Runtime Environment has been installed on the Self-hosted Integration Runtime machine.,Source=Microsoft.DataTransfer.Common,Type=System.DllNotFoundException,Message=Unable to load DLL jvm.dll: The specified module could not be found. (Exception from HRESULT: 0x8007007E),Source=Microsoft.DataTransfer.Common.JavaUtils,	Create_Snowflake_Objects
a62112a9-a784-4370-9ebe-a1e81c86b1cb		2025-08-29 10:59:22.683	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Apache.Arrow.Adbc.C.CAdbcDriverImporter+ImportedAdbcException,Message=[Snowflake] 002003 (02000): SQL compilation error:
Schema STAGE_DEV.BIDPROCESS_DBO_LANDING does not exist or not authorized.,Source=Apache.Arrow.Adbc,	Create_Snowflake_Objects
e5043cd0-3d99-4a18-8d2c-e36a81e044d3		2025-08-07 11:55:12.310	Operation on target Full Load SQL Server Data failed: Type=System.OutOfMemoryException,Message=Exception of type System.OutOfMemoryException was thrown.,Source=Microsoft.DataTransfer.ClientLibrary,	Create_Snowflake_Objects
6173c7ff-67fb-42f0-87c8-3960381d464c		2025-11-14 07:09:02.610	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects
6897575a-28b4-4851-a2e0-1f079b97f0b0		2025-12-16 07:58:32.683	Error Detected, check ADF logs	Create_Snowflake_Objects
f33a7a86-81be-4c70-b991-f3af7d2cdce2		2025-11-13 12:54:27.292	Operation on target Get SQL Server Table Metadata failed: ErrorCode=SqlFailedToConnect,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Cannot connect to SQL Database. Please contact SQL server team for further support. Server: SHAREDSQL-TEST, Database: PathEmbraceODS, User: scansvc-heart-adf-np. Check the linked service configuration is correct, and make sure the SQL Database firewall allows the integration runtime to access.,Source=Microsoft.DataTransfer.Connectors.MSSQL,Type=Microsoft.Data.SqlClient.SqlException,Message=Cannot open database "PathEmbraceODS" requested by the login. The login failed.
Login failed for user SCANSVC-HEART-ADF-NP.,Source=Framework Microsoft SqlClient Data Provider,	Create_Snowflake_Objects
6173c7ff-67fb-42f0-87c8-3960381d464c		2025-11-14 07:12:29.605	Operation on target Create Stage Table if Not Exists failed: Failed to execute script. Exception: Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to execute the query command during read operation.,Source=Microsoft.DataTransfer.Execution.ScriptActivityExecutor,Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Missing table or query for Snowflake Connector,Source=Microsoft.Connectors.SnowflakeV2,	Create_Snowflake_Objects